import { Inter,Luckiest_Guy } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const luckiestGuy = Luckiest_Guy({ subsets: ["latin"],
  variable:"--font-luckiest-guy",
  weight: "400"
 });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${luckiestGuy.variable}`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
